version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 900
      runas: ec2-user
  AfterInstall:
    - location: scripts/deploy_laravel.sh
      timeout: 900
      runas: ec2-user
    - location: scripts/change_permissions.sh
      timeout: 900
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 920
      runas: ec2-user    
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 920
      runas: ec2-user
